POST http://localhost:5000/v1/user
Content-Type: application/json

{
    "name":"rohit",
    "address":"giridih",
    "phone":"555666",
    "email":"rohit@gmail.com",
    "password":"123456789"
}


###

POST http://localhost:5000/v1/user/login
Content-Type: application/json

{
    "email":"rohit@gmail.com",
    "password":"123456789"
}